// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzTgcZbARuyd2cPAQC8h-0TIsn6HiIA8c',
    appId: '1:442197865520:web:ff9a2847ab4e3ab17169f5',
    messagingSenderId: '442197865520',
    projectId: 'drooti-71c64',
    authDomain: 'drooti-71c64.firebaseapp.com',
    storageBucket: 'drooti-71c64.appspot.com',
    measurementId: 'G-MM02B46HHP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-3601UuAWf35szKwq7ikTT4YXOzeKfYo',
    appId: '1:442197865520:android:ad53b79abacb6b697169f5',
    messagingSenderId: '442197865520',
    projectId: 'drooti-71c64',
    storageBucket: 'drooti-71c64.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAFDoGmiIk5nGcQ9ljP5TeYsUpa0oR59s',
    appId: '1:442197865520:ios:dc05054bf631bd2f7169f5',
    messagingSenderId: '442197865520',
    projectId: 'drooti-71c64',
    storageBucket: 'drooti-71c64.appspot.com',
    iosClientId: '442197865520-1s1nblrpn7pkfdo0qrrcg0lmb2vuci1u.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAFDoGmiIk5nGcQ9ljP5TeYsUpa0oR59s',
    appId: '1:442197865520:ios:dc05054bf631bd2f7169f5',
    messagingSenderId: '442197865520',
    projectId: 'drooti-71c64',
    storageBucket: 'drooti-71c64.appspot.com',
    iosClientId: '442197865520-1s1nblrpn7pkfdo0qrrcg0lmb2vuci1u.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
